### ISSUE TITLE
playbook not working?

### ISSUE THREAD

**Issue by 2sn** [ADACS-Australia/starfit-server#16]
when I run the playbook for `starfit.xyz` I get the error message:
```
TASK [starfit : Run code to generate matplotlib and tex caches] ****************************************************************
fatal: [sfx]: FAILED! => changed=true 
  cmd: sudo -u apache MPLCONFIGDIR=/usr/share/httpd/mplconfig.d python -c "import starfit; starfit.Single('HE1327-2326.dat').plot()"
  delta: '0:00:00.678221'
  end: '2022-10-16 11:03:22.349538'
  msg: non-zero return code
  rc: 1
  start: '2022-10-16 11:03:21.671317'
  stderr: |-
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib64/python3.10/site-packages/starfit/fit.py", line 38, in __init__
        self._setup(
      File "/usr/local/lib64/python3.10/site-packages/starfit/starfit.py", line 73, in _setup
        if not dbname.is_file():
      File "/usr/lib64/python3.10/pathlib.py", line 1322, in is_file
        return S_ISREG(self.stat().st_mode)
      File "/usr/lib64/python3.10/pathlib.py", line 1097, in stat
        return self._accessor.stat(self, follow_symlinks=follow_symlinks)
    PermissionError: [Errno 13] Permission denied: 'znuc2012.S4.star.el.y.stardb.gz'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

PLAY RECAP *********************************************************************************************************************
sfx                        : ok=19   changed=3    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
```

**Comment by 2sn** [comment]
This may be an issue with the refactored reader

**Comment by 2sn** [comment]
fixed by https://github.com/conradtchan/starfit/pull/45
